/* FLP Dashboard. Datos y cálculos independientes de la presentación. */
(function(global){
'use strict';
const DAY=86400000;
const clean=v=>v==null?'':String(v).trim().replace(/\s+/g,' ');
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function money(v){
 if(typeof v==='number')return Number.isFinite(v)?v:null;
 let s=clean(v).replace(/MXN|USD|\$/gi,'').replace(/\s/g,'');if(!s)return null;
 if(/^[-+]?\d+(\.\d+)?$/.test(s))return Number(s);
 if(/^[-+]?\d{1,3}(,\d{3})+(\.\d{1,2})?$/.test(s))return Number(s.replace(/,/g,''));
 if(/^[-+]?\d+,\d{1,2}$/.test(s))return Number(s.replace(',','.'));
 return null;
}
function date(v,date1904=false){
 if(v instanceof Date)return Number.isFinite(+v)?+v:null;
 if(typeof v==='number'&&Number.isFinite(v)&&v>0){const x=(v-(date1904?24107:25569))*DAY;return Number.isFinite(x)?x:null;}
 const s=clean(v);let m=s.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})(?:[ T](\d{1,2}):(\d{2})(?::(\d{2})(?:\.\d+)?)?)?(?:Z|[+-]\d{2}:?\d{2})?$/);
 let y,mo,d,h=0,mi=0,se=0;
 if(m){[y,mo,d,h,mi,se]=[+m[1],+m[2],+m[3],+(m[4]||0),+(m[5]||0),+(m[6]||0)];}
 else {m=s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);if(!m)return null;[y,mo,d,h,mi,se]=[+m[3],+m[2],+m[1],+(m[4]||0),+(m[5]||0),+(m[6]||0)];}
 const x=Date.UTC(y,mo-1,d,h,mi,se),dt=new Date(x);return dt.getUTCFullYear()===y&&dt.getUTCMonth()===mo-1&&dt.getUTCDate()===d&&h<24&&mi<60&&se<60?x:null;
}
function duration(v){
 if(typeof v==='number')return Number.isFinite(v)&&v>=0?v*86400:null;
 const s=clean(v);const m=s.match(/^(\d+):(\d{2}):(\d{2})(?:\.(\d+))?$/);if(m&&+m[2]<60&&+m[3]<60)return +m[1]*3600 + +m[2]*60 + +m[3]+(m[4]?Number('0.'+m[4]):0);return null;
}
function bool(v){const s=norm(v);if(['si','yes','true','1','resuelto','resuelta'].includes(s))return true;if(['no','false','0','no resuelto'].includes(s))return false;return null;}
const iso=t=>new Date(t).toISOString().slice(0,10);
const midnight=t=>Math.floor(t/DAY)*DAY;
const week=t=>{const dt=new Date(midnight(t));return +dt-((dt.getUTCDay()+6)%7)*DAY;};
const key=(t,g)=>g==='month'?iso(t).slice(0,7):g==='week'?iso(week(t)):iso(t);
const aliases={
 calls:{agent:['Agente','Operador','Ejecutivo'],start:['Hora Inicio','Fecha Inicio','Inicio','Fecha'],end:['Hora Fin','Fin'],talk:['Duración','Duracion','Tiempo Atencion','Tiempo Atención'],wait:['Tiempo Espera','Espera'],region:['Cola','Campaña','Centro','Sucursal'],status:['Estado','Estatus','Resultado'],type:['Tipo'],fcr:['FCR','Resolución en primer contacto','Resolucion Primer Contacto']},
 sales:{agent:['EJECUTIVO','Agente','Vendedor'],date:['FECHA','Fecha venta'],region:['ESTADO','Region','Región'],branch:['SUCURSAL','Centro'],ticket:['ORDEN / TICKET','Ticket','Orden','ID venta'],amount:['TOTAL','Importe','Venta','Monto'],service:['SERVICIO','Producto','Categoria','Categoría','Servicio'],opportunities:['OPORTUNIDADES','Leads'],conversions:['CONVERSIONES','Conversiones realizadas']}
};
const fieldNames={agent:'Agente / ejecutivo',start:'Hora Inicio',end:'Hora Fin',talk:'Duración',wait:'Tiempo Espera',region:'Cola / estado / región',status:'Estado de llamada',type:'Tipo',fcr:'FCR',date:'FECHA',branch:'SUCURSAL',ticket:'ORDEN / TICKET',amount:'TOTAL',service:'SERVICIO / producto',opportunities:'OPORTUNIDADES',conversions:'CONVERSIONES'};
function guess(headers,type){return Object.fromEntries(Object.entries(aliases[type]).map(([k,a])=>[k,headers.findIndex(h=>a.some(x=>norm(x)===norm(h)))]));}
function normalize(source,type,dedup=true){
 const mapping=source.mapping||guess(source.headers,type);const get=(r,k)=>mapping[k]>=0?r[mapping[k]]:null;
 const q={raw:source.rows.length,duplicates:0,invalidDate:0,invalidMoney:0,missingTalk:0,missingWait:0,estimated:0,endFallback:0,missingTicket:0,unknownStatus:0,fcrValid:0,conversionValid:0,negativeMoney:0,issues:[]};
 const seen=new Set(),data=[];const labels={};
 const label=(v,fallback='Sin dato')=>{const s=clean(v)||fallback;const n=norm(s);if(!labels[n])labels[n]=s;return labels[n];};
 source.rows.forEach((r,i)=>{
  if(!r.some(v=>v!=null&&clean(v)!==''))return;
  const fingerprint=source.keys?.[i]||JSON.stringify(r);const duplicate=seen.has(fingerprint);if(duplicate)q.duplicates++;seen.add(fingerprint);if(duplicate&&dedup)return;
  const agent=label(get(r,'agent'),'Sin asignar');
  if(type==='calls'){
   const start=date(get(r,'start'),source.date1904),end=date(get(r,'end'),source.date1904),wait=duration(get(r,'wait')),talk=duration(get(r,'talk'));let t=start,estimated=false;
   if(t===null&&end!==null){if(wait!==null){t=end-wait*1000;q.estimated++;}else{t=end;q.endFallback++;}estimated=true;}
   if(t===null){q.invalidDate++;q.issues.push(`Fila ${i+2}: fecha no válida.`);return;}
   const status=label(get(r,'status'));const sn=norm(status),answered=['atendido','atendida','contestada','contestado','answered'].includes(sn),abandoned=['abandono','abandonada','abandonado','abandoned'].includes(sn);
   if(!answered&&!abandoned)q.unknownStatus++;
   if(wait===null)q.missingWait++;if(answered&&talk===null)q.missingTalk++;
   const fcr=bool(get(r,'fcr'));if(answered&&fcr!==null)q.fcrValid++;
   data.push({t,date:iso(t),agent,region:label(get(r,'region')),type:label(get(r,'type')),status,answered,abandoned,wait,talk,fcr,estimated,id:i+1});
  }else{
   const t=date(get(r,'date'),source.date1904);if(t===null){q.invalidDate++;q.issues.push(`Fila ${i+2}: fecha no válida.`);return;}
   const amount=money(get(r,'amount'));if(amount===null){q.invalidMoney++;q.issues.push(`Fila ${i+2}: TOTAL no válido «${clean(get(r,'amount'))}».`);}else if(amount<0)q.negativeMoney++;
   const branch=label(get(r,'branch')),ticket=clean(get(r,'ticket'));const ticketValid=ticket&&!/^(sin\s*(informacion|inf|dato)|n\/a|na|-)$/i.test(norm(ticket));if(!ticketValid)q.missingTicket++;
   const opportunities=money(get(r,'opportunities')),conversions=money(get(r,'conversions'));const conversionValid=opportunities!==null&&opportunities>=0&&conversions!==null&&conversions>=0&&conversions<=opportunities;if(conversionValid)q.conversionValid++;
   data.push({t:midnight(t),date:iso(t),agent,region:label(get(r,'region')),branch,ticket:ticket||'Sin ticket',transaction:ticketValid?JSON.stringify([iso(t),norm(branch),ticket]):'row:'+i,amount,service:label(get(r,'service')),opportunities,conversions,conversionValid,id:i+1});
  }
 });return {data,q,mapping,name:source.name};
}
const sum=(a,f)=>a.reduce((s,r)=>s+(f(r)||0),0);
const avg=a=>a.length?sum(a,x=>x)/a.length:null;
const ratio=(a,b)=>b?a/b:null;
function metrics(rows,type,threshold=20){if(type==='calls'){const answered=rows.filter(r=>r.answered),abandoned=rows.filter(r=>r.abandoned),fcr=answered.filter(r=>r.fcr!==null);return {total:rows.length,answered:answered.length,abandoned:abandoned.length,attention:ratio(answered.length,rows.length),aht:avg(answered.filter(r=>r.talk!==null).map(r=>r.talk)),wait:avg(rows.filter(r=>r.wait!==null).map(r=>r.wait)),sla:ratio(answered.filter(r=>r.wait!==null&&r.wait<=threshold).length,rows.length),fcr:ratio(fcr.filter(r=>r.fcr).length,fcr.length),fcrN:fcr.length};}const valid=rows.filter(r=>r.amount!==null),conv=rows.filter(r=>r.conversionValid),transactions=new Set(rows.map(r=>r.transaction)).size,validTransactions=new Set(valid.map(r=>r.transaction)).size;return {total:sum(valid,r=>r.amount),transactions,validTransactions,average:ratio(sum(valid,r=>r.amount),validTransactions),conversion:ratio(sum(conv,r=>r.conversions),sum(conv,r=>r.opportunities)),conversionN:conv.length,invalidMoney:rows.length-valid.length};}
function inService(r){const t=new Date(r.t);const minutes=t.getUTCHours()*60+t.getUTCMinutes()+t.getUTCSeconds()/60;return minutes>=8*60&&minutes<23*60;}
function weekNumber(t){const d=new Date(midnight(t));d.setUTCDate(d.getUTCDate()+3-((d.getUTCDay()+6)%7));const year=d.getUTCFullYear(),first=new Date(Date.UTC(year,0,4));first.setUTCDate(first.getUTCDate()+3-((first.getUTCDay()+6)%7));return {year,number:1+Math.round((d-first)/(7*DAY))};}
function filter(rows,f={}){return rows.filter(r=>(f.type!=='calls'||inService(r))&&(!f.month||r.date.slice(0,7)===f.month)&&(!f.from||r.date>=f.from)&&(!f.to||r.date<=f.to)&&(!f.agent||norm(r.agent)===norm(f.agent))&&(!f.region||norm(r.region)===norm(f.region))&&(!f.segment||norm(r[f.type==='sales'?'service':'status'])===norm(f.segment))&&(!f.branch||norm(r.branch)===norm(f.branch))&&(f.hour===undefined||new Date(r.t).getUTCHours()===f.hour)&&(f.weekday===undefined||(new Date(r.t).getUTCDay()+6)%7===f.weekday));}
function group(rows,field){const m=new Map();rows.forEach(r=>{const k=typeof field==='function'?field(r):r[field];if(!m.has(k))m.set(k,[]);m.get(k).push(r);});return [...m].sort((a,b)=>String(a[0]).localeCompare(String(b[0])));}
function series(rows,g,from,to){if(!rows.length||!from||!to)return [];const grouped=new Map(group(rows,r=>key(r.t,g)));let t=date(from),end=date(to);if(g==='week')t=week(t);if(g==='month'){const d=new Date(t);t=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1);}const out=[];let guard=0;while(t<=end&&guard++<10000){const k=key(t,g);out.push([k,grouped.get(k)||[]]);if(g==='month'){const d=new Date(t);t=Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1);}else t+=DAY*(g==='week'?7:1);}return out;}
function compare(rows,filters,type,threshold){const anchor=date(filters.to),w=week(anchor),days=Math.floor((midnight(anchor)-w)/DAY);const curr=filter(rows,{...filters,type,month:'',from:iso(w),to:iso(w+days*DAY)}),prev=filter(rows,{...filters,type,month:'',from:iso(w-7*DAY),to:iso(w-7*DAY+days*DAY)});return {curr:metrics(curr,type,threshold),prev:metrics(prev,type,threshold),currRows:curr,prevRows:prev,from:iso(w),previous:iso(w-7*DAY),days:days+1};}
function linearTrend(values){const valid=values.map((y,x)=>({x,y})).filter(p=>typeof p.y==='number'&&Number.isFinite(p.y));if(valid.length<2)return values.map(()=>null);const mx=avg(valid.map(p=>p.x)),my=avg(valid.map(p=>p.y));const denominator=sum(valid,p=>(p.x-mx)**2);if(!denominator)return values.map(()=>null);const slope=sum(valid,p=>(p.x-mx)*(p.y-my))/denominator;return values.map((_,x)=>my+slope*(x-mx));}
function rankExecutives(rows,by='total'){return group(rows,'agent').filter(g=>!['sucursal','sin asignar','sin dato'].includes(norm(g[0]))).map(([name,records])=>({name,records,...metrics(records,'sales')})).sort((a,b)=>(b[by]-a[by])||(b.total-a.total)||a.name.localeCompare(b.name,'es'));}
function monthlyCalls(rows,from,to){return series(rows,'month',from,to).map(([month,data])=>({month,...metrics(data,'calls')}));}
function hourlyCalls(rows){const buckets=Array.from({length:15},()=>[]);rows.forEach(r=>{if(inService(r))buckets[new Date(r.t).getUTCHours()-8].push(r);});return buckets.map((data,i)=>({hour:i+8,...metrics(data,'calls')}));}
const api={DAY,clean,norm,money,date,duration,bool,iso,week,key,guess,normalize,metrics,filter,group,series,compare,inService,weekNumber,linearTrend,rankExecutives,monthlyCalls,hourlyCalls,fieldNames,aliases};global.FLPCore=api;
})(typeof window!=='undefined'?window:globalThis);

(function(){
'use strict';if(typeof document==='undefined')return;
const C=window.FLPCore,$=s=>document.getElementById(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=new Intl.NumberFormat('es-MX'),moneyFmt=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}),preciseMoney=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',minimumFractionDigits:2});
const fmt=n=>number.format(n),cash=n=>n===null?'—':moneyFmt.format(n),pct=n=>n===null?'—':(n*100).toFixed(1)+'%',time=n=>n===null?'—':`${Math.floor(Math.round(n)/60)}:${String(Math.round(n)%60).padStart(2,'0')} min`;
const dt=s=>new Date(C.date(s)).toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
const monthNames=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
function monthLabel(k){return monthNames[+k.slice(5,7)-1]+(state.f.from.slice(0,4)!==state.f.to.slice(0,4)?' '+k.slice(0,4):'');}
function periodLabel(k){if(state.grain==='month')return monthLabel(k);if(state.grain==='week')return `Semana ${String(C.weekNumber(C.date(k)).number).padStart(2,'0')}`;return dt(k);}
const colors=['#087f8c','#3767cd','#d5656b','#d99730','#8a6bc5','#62b2b5','#7189a7','#af7561','#679949','#c17eb2','#7bb7dc','#b2b7c1'];
const state={type:'calls',raw:{calls:{headers:[],rows:[],name:"llamadas.xlsx"},sales:{headers:[],rows:[],name:"ventas.xlsx"}},datasets:{},f:{from:'',to:'',month:'',agent:'',region:'',segment:'',type:'calls'},dimensions:{calls:{agent:'',region:'',segment:''},sales:{agent:'',region:'',segment:''}},cross:{},grain:'week',grains:{calls:'week',sales:'month'},theme:'light',sla:20,slaGoal:80,salesGoal:0,dedup:true,charts:[],remote:{loading:false,loadedAt:null,error:''}};
function rebuild(){for(const t of ['calls','sales'])state.datasets[t]=C.normalize(state.raw[t],t,state.dedup);}
function bounds(){const dates=Object.values(state.datasets).flatMap(d=>d.data.map(r=>r.date));const today=new Date().toISOString().slice(0,10);return {min:dates.length?dates.reduce((a,b)=>a<b?a:b):today,max:dates.length?dates.reduce((a,b)=>a>b?a:b):today};}
function message(s,error=false){$('message').hidden=!s;$('message').textContent=s||'';$('message').style.background=error?'#fff0f0':'';}
function fill(id,values,selected,all){$(id).innerHTML=`<option value="">${all}</option>`+[...new Set(values)].sort((a,b)=>a.localeCompare(b,'es')).map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('');}
function setupFilters(){const data=state.datasets[state.type].data;fill('agentFilter',data.map(r=>r.agent),state.f.agent,'Todos');fill('segmentFilter',data.map(r=>r[state.type==='calls'?'status':'service']),state.f.segment,state.type==='calls'?'Todos los estados':'Todos los servicios');const months=[...new Set(Object.values(state.datasets).flatMap(d=>d.data.map(r=>r.date.slice(0,7))))].sort();$('monthFilter').innerHTML='<option value="">Todos los meses</option>'+months.map(k=>{const name=new Date(C.date(k+'-01')).toLocaleDateString('es-MX',{month:'long',year:'numeric',timeZone:'UTC'});return `<option value="${k}" ${state.f.month===k?'selected':''}>${name.charAt(0).toUpperCase()+name.slice(1)}</option>`;}).join('');$('segmentLabel').textContent=state.type==='calls'?'Estado de llamada':'Servicio / categoría';$('fromDate').value=state.f.from;$('toDate').value=state.f.to;$('grain').value=state.grain;}
function selectMonth(value){if(value&&(!/^\d{4}-\d{2}$/.test(value)||C.date(value+'-01')===null))throw Error('Mes inválido');state.f.month=value;const b=bounds();if(value){state.grain='month';state.grains={calls:'month',sales:'month'};const start=C.date(value+'-01');if(start===null)throw Error('Mes inválido');const d=new Date(start);state.f.from=value+'-01';state.f.to=C.iso(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0));}else{state.f.from=b.min;state.f.to=b.max;}state.cross={};setupFilters();render();}
function applyTheme(value,persist=true){if(!['light','dark'].includes(value))throw Error('Modo inválido');state.theme=value;document.documentElement.dataset.theme=value;document.documentElement.style.colorScheme=value;$('themeToggle').setAttribute('aria-checked',String(value==='dark'));$('themeToggle').title=value==='dark'?'Desactivar modo oscuro':'Activar modo oscuro';$('themeIcon').innerHTML=value==='dark'?'<path d="M20.5 13A8.5 8.5 0 0 1 11 3.5 8.5 8.5 0 1 0 20.5 13Z"/>':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>';if(persist)try{localStorage.setItem('flp-theme',value);}catch(_){}if(window.Chart)Chart.defaults.color=value==='dark'?'#b9c9dc':'#63738a';render();}
function setTab(type){if(!['calls','sales'].includes(type))throw Error('Área no válida');state.dimensions[state.type]={agent:state.f.agent,region:state.f.region,segment:state.f.segment};state.grains[state.type]=state.grain;state.type=type;state.grain=state.grains[type];state.f={...state.f,...state.dimensions[type],type};state.cross={};for(const t of ['Calls','Sales']){$('tab'+t).classList.toggle('active',t.toLowerCase()===type);$('tab'+t).setAttribute('aria-selected',String(t.toLowerCase()===type));}$('dashboard').setAttribute('aria-labelledby',type==='calls'?'tabCalls':'tabSales');setupFilters();render();}
function getFilters(){return {...state.f,...state.cross,type:state.type};}
function rows(){return C.filter(state.datasets[state.type].data,getFilters());}
function cross(field,value){if(field==='date'){state.f.month='';state.f.from=value;state.f.to=value;setupFilters();}else if(field==='period'){state.f.month='';state.f.from=value.from;state.f.to=value.to;setupFilters();}else if(['agent','region','segment'].includes(field)){state.f[field]=state.f[field]===value?'':value;setupFilters();}else{if(state.cross[field]===value)delete state.cross[field];else state.cross[field]=value;}render();}
function card(label,value,detail,icon,cls=''){return `<article class="kpi ${cls}"><div class="kpi-label">${label}<span class="kpi-icon" aria-hidden="true">${icon}</span></div><div class="kpi-value">${value}</div><div class="kpi-detail">${detail}</div></article>`;}
function panel(id,title,subtitle,foot='',cls='',badge=''){return `<article class="panel ${cls}"><div class="panel-head"><div><h2>${title}</h2><p>${subtitle}</p></div>${badge?`<span class="panel-number">${badge}</span>`:''}</div><div class="chartbox" id="box-${id}"><canvas id="${id}" aria-label="${esc(title)}" role="img"></canvas></div>${foot?`<div class="panel-foot">${foot}</div>`:''}</article>`;}
function empty(id,heading,text){$('box-'+id).innerHTML=`<div class="empty"><span class="dash">—</span><strong>${esc(heading)}</strong><p>${esc(text)}</p></div>`;}
function chart(id,type,labels,datasets,options={},click=null){
 if(!window.Chart){empty(id,'Gráfico no disponible','Recarga el dashboard.');return;}
 const horizontal=options.indexAxis==='y',moneyScale=options.moneyScale;delete options.moneyScale;
 const base={responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:type==='line'?'index':'nearest',intersect:type!=='line'},plugins:{legend:{display:datasets.length>1||type==='doughnut',position:'bottom',labels:{usePointStyle:true,boxWidth:8,padding:15,font:{size:12},color:'#63738a'}},tooltip:{backgroundColor:'#122238',padding:12,titleFont:{size:12},bodyFont:{size:12},callbacks:{label:ctx=>`${ctx.dataset.label||ctx.label}: ${moneyScale?preciseMoney.format(ctx.parsed[horizontal?'x':'y']??ctx.parsed):fmt(ctx.parsed[horizontal?'x':'y']??ctx.parsed)}`}}},scales:type==='doughnut'?{}:{x:{grid:{display:horizontal},border:{display:false},ticks:{maxRotation:0,autoSkip:true,maxTicksLimit:9,color:'#63738a',font:{size:12}},...(horizontal?{beginAtZero:true}:{})},y:{beginAtZero:true,grid:{color:'#edf1f5',display:!horizontal},border:{display:false},ticks:{color:'#63738a',font:{size:12}}}}};
 const merged={...base,...options,plugins:{...base.plugins,...options.plugins},scales:{...base.scales,...options.scales}};
 const text=state.theme==='dark'?'#b9c9dc':'#63738a',grid=state.theme==='dark'?'#2b4057':'#edf1f5';if(merged.plugins.legend?.labels)merged.plugins.legend.labels.color=text;for(const axis of Object.values(merged.scales||{})){axis.ticks={...axis.ticks,color:text};axis.grid={...axis.grid,color:grid};}
 if(click){merged.onClick=(_,els)=>{if(els.length)click(els[0].index,els[0].datasetIndex);};merged.onHover=(event,els)=>{event.native.target.style.cursor=els.length?'pointer':'default';};}
 const c=new Chart($(id),{type,data:{labels,datasets:datasets.map((d,i)=>({borderRadius:type==='bar'?4:undefined,borderWidth:type==='doughnut'?3:0,backgroundColor:colors[i],borderColor:colors[i],...d}))},options:merged});state.charts.push(c);return c;
}
function line(id,ser,dsets,click,money=false){chart(id,'line',ser.map(s=>state.type==='calls'?periodLabel(s[0]):state.grain==='month'?s[0]:dt(s[0]).replace(/ de \d{4}/,'')),dsets.map((d,i)=>({label:d.label,data:ser.map(s=>d.get(s[1])),borderColor:colors[i],backgroundColor:i===0?'#087f8c12':'#3767cd10',borderWidth:2,fill:i===0,tension:.3,pointRadius:ser.length>45?0:2,pointHitRadius:10})),{moneyScale:money,scales:{x:{grid:{display:false},ticks:{autoSkip:state.grain!=='month',maxTicksLimit:9,maxRotation:0,font:{size:12}}}}},click);}
function bar(id,groups,get,label,field,money=false){const sorted=[...groups].sort((a,b)=>get(b[1])-get(a[1])).slice(0,10);chart(id,'bar',sorted.map(g=>g[0]),[{label,data:sorted.map(g=>get(g[1])),backgroundColor:sorted.map((_,i)=>i===0?colors[0]:'#89bfc6')}],{indexAxis:'y',moneyScale:money},field?(i)=>cross(field,sorted[i][0]):null);return sorted;}
function donut(id,groups,get,label,field,money=false,showPercent=false){const sorted=[...groups].sort((a,b)=>get(b[1])-get(a[1])),total=sorted.reduce((n,g)=>n+get(g[1]),0);const labels=sorted.map(g=>showPercent?`${g[0]} · ${pct(total?get(g[1])/total:null)}`:g[0]);const options={cutout:'70%',moneyScale:money};if(showPercent)options.plugins={tooltip:{backgroundColor:'#122238',padding:12,callbacks:{label:ctx=>`${sorted[ctx.dataIndex][0]}: ${fmt(ctx.parsed)} llamadas (${pct(total?ctx.parsed/total:null)})`}}};chart(id,'doughnut',labels,[{label,data:sorted.map(g=>get(g[1])),backgroundColor:colors}],options,field?(i)=>cross(field,sorted[i][0]):null);}
function gauge(id,value,label,note){if(value===null){empty(id,'Sin datos suficientes',note);return;}const shown=Math.min(1,Math.max(0,value));$('box-'+id).innerHTML=`<div class="gauge-shell"><div class="gauge"><canvas id="${id}" aria-label="${esc(label)} ${pct(value)}" role="img"></canvas><div class="gauge-center">${pct(value)}</div></div><div class="gauge-label">${esc(label)}</div><div class="mini-note">${esc(note)}</div></div>`;chart(id,'doughnut',['Logrado','Restante'],[{data:[shown*100,100-shown*100],backgroundColor:[colors[0],'#e8edf3'],borderWidth:0}],{rotation:-90,circumference:180,cutout:'82%',plugins:{legend:{display:false},tooltip:{enabled:false}}});}
function trendCross(ser,i){const k=ser[i][0];if(state.grain==='day')cross('date',k);else{const t=C.date(k.length===7?k+'-01':k),d=new Date(t);const end=state.grain==='week'?t+6*C.DAY:Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0);cross('period',{from:k.length===7?k+'-01':k,to:C.iso(end)});}}
function render(){
 const f=getFilters();if(f.from>f.to){message('La fecha Desde debe ser anterior o igual a Hasta.',true);return;}message(state.remote.error,!!state.remote.error);
 state.charts.forEach(c=>c.destroy());state.charts=[];
 const data=rows(),all=C.filter(state.datasets[state.type].data,{type:state.type}),m=C.metrics(data,state.type,state.sla),ser=C.series(data,state.grain,f.from,f.to),comp=C.compare(all,f,state.type,state.sla);
 const last=all.length?all.reduce((a,r)=>a>r.date?a:r.date,''):'';
 $('freshness').innerHTML=`Corte ${state.type==='calls'?'operativo':'comercial'}<br><b>${last?dt(last):'Sin fecha válida'}</b>`;
 $('periodText').textContent=`${dt(f.from)} — ${dt(f.to)} · ${state.type==='calls'?'Operaciones de llamadas · servicio 08:00–23:00':'Desempeño comercial'} · MXN`;
 $('scopeText').textContent=`${fmt(data.length)} de ${fmt(all.length)} registros · ${state.datasets[state.type].name}`;
 const crossNames=[];if(state.f.region)crossNames.push(state.f.region);if(state.cross.hour!==undefined)crossNames.push(`${state.cross.hour}:00 h`);if(state.cross.weekday!==undefined)crossNames.push(['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'][state.cross.weekday]);if(state.cross.branch)crossNames.push(state.cross.branch);
 $('crossText').innerHTML=crossNames.length?`Selección: ${esc(crossNames.join(' · '))} <button id="clearCross">Quitar</button>`:'Selecciona una barra o un segmento para filtrar';if($('clearCross'))$('clearCross').onclick=()=>{state.cross={};state.f.region='';setupFilters();render();};
 if(state.type==='calls')renderCalls(data,m,ser,comp);else renderSales(data,m,ser,comp);
 if(!data.length){$('insights').innerHTML='<span class="insight-label">SIN RESULTADOS</span><span>Amplía el período o limpia los filtros para consultar los datos disponibles.</span>';[...$('charts').querySelectorAll('.chartbox')].forEach(b=>{if(b.querySelector('canvas'))b.insertAdjacentHTML('beforeend','<span class="sr-only">No hay registros para esta selección.</span>');});}
 renderTable(data);quality();
}
function renderCalls(data,m,ser,comp){
 const volumeSeries=state.grain==='day'?ser.slice(-30):ser;const dayWindow=state.grain==='day'&&volumeSeries.length?`Hasta 30 días · ${dt(volumeSeries[0][0])} — ${dt(volumeSeries[volumeSeries.length-1][0])}`:'Evolución del período seleccionado';
 $('kpis').innerHTML=card('Total de llamadas',fmt(m.total),`${fmt(m.answered)} atendidas · ${fmt(m.abandoned)} abandonadas`,'☎')+card('Tasa de atención',pct(m.attention),`${pct(C.metrics(data,'calls').total?m.abandoned/m.total:null)} de abandono`,'✓')+card('AHT observado',time(m.aht),'Duración de atención · sin trabajo posterior','◷')+card(`SLA ≤ ${state.sla} s`,pct(m.sla),`Objetivo configurable: ${state.slaGoal}% de todas las llamadas`,'◎');
 const top=C.group(data,'agent').filter(g=>g[0]!=='Sin asignar').sort((a,b)=>b[1].length-a[1].length)[0];
 $('insights').innerHTML=`<span class="insight-label">LECTURA DEL PERÍODO</span><span>${data.length?`<b>${esc(top?.[0]||'Sin asignar')}</b> concentra ${top?pct(top[1].length/data.length):'—'} del volumen. Espera promedio: <b>${time(m.wait)}</b>. ${m.sla!==null&&m.sla*100<state.slaGoal?'El SLA está por debajo del objetivo configurado.':'Revisa la carga horaria para planear cobertura.'}`:'No hay llamadas para la selección.'}</span>`;
 $('charts').innerHTML=panel('callTrend','Volumen de llamadas',dayWindow,'Haz clic en un punto para consultar ese período.','wide',state.grain==='week'?'SEMANAL':state.grain==='month'?'MENSUAL':'DIARIO')+panel('callTimes','Espera vs. atención','Promedios del período · segundos','Atención: Duración solo de atendidas.','wide')+panel('callStatus','Estado de las llamadas','Atención y abandono','Selecciona un segmento para filtrar.')+panel('callHours','Tráfico por hora','Ventana de servicio 08:00–23:00','Cada barra representa una hora de servicio. Incluye horas estimadas de abandonos.')+panel('callAgents','Desempeño por agente','Top 10 por volumen asignado','La atención se consulta al seleccionar un agente.')+panel('callAbandon','Atención vs. abandono','Porcentaje de llamadas por período','Pasa el cursor para ver porcentaje y volumen.','wide')+panel('callCompare','Semana actual vs. anterior','Períodos de igual duración','','wide')+monthlyPanel()+hourlyPanel()+panel('callHeat','Mapa de tráfico','Día de la semana × hora','Selecciona una celda para filtrar día y hora.','full');
 line('callTrend',volumeSeries,[{label:'Llamadas',get:r=>r.length}],i=>trendCross(volumeSeries,i));
 donut('callStatus',C.group(data,'status'),r=>r.length,'Llamadas','segment',false,true);
 const hours=Array.from({length:15},(_,i)=>i+8),hrs=hours.map(h=>data.filter(r=>new Date(r.t).getUTCHours()===h));chart('callHours','bar',hours.map(h=>`${String(h).padStart(2,'0')}:00–${String(h+1).padStart(2,'0')}:00`), [{label:'Llamadas',data:hrs.map(r=>r.length),backgroundColor:hrs.map(r=>r.length===Math.max(...hrs.map(x=>x.length))?colors[0]:'#a7cdd2')}],{scales:{x:{grid:{display:false},ticks:{maxTicksLimit:15,maxRotation:0,font:{size:12}}},y:{beginAtZero:true,grid:{color:'#edf1f5'}}}},i=>cross('hour',hours[i]));
 const agents=C.group(data,'agent').filter(g=>C.norm(g[0])!=='sin asignar').sort((a,b)=>b[1].length-a[1].length).slice(0,10);chart('callAgents','bar',agents.map(g=>g[0]),[{label:'Atendidas',data:agents.map(g=>g[1].filter(r=>r.answered).length),backgroundColor:colors[0]},{label:'Abandonadas',data:agents.map(g=>g[1].filter(r=>r.abandoned).length),backgroundColor:colors[2]},{label:'Otros',data:agents.map(g=>g[1].filter(r=>!r.answered&&!r.abandoned).length),backgroundColor:'#aab7c8'}],{indexAxis:'y',scales:{x:{stacked:true,beginAtZero:true,grid:{color:'#edf1f5'}},y:{stacked:true,grid:{display:false},ticks:{font:{size:12},color:'#63738a'}}}},i=>cross('agent',agents[i][0]));
 line('callTimes',ser,[{label:'Espera (s)',get:r=>C.metrics(r,'calls').wait},{label:'Atención (s)',get:r=>C.metrics(r,'calls').aht}],i=>trendCross(ser,i));
 const statusFns=[r=>r.answered,r=>r.abandoned,r=>!r.answered&&!r.abandoned];chart('callAbandon','bar',ser.map(s=>periodLabel(s[0])),['Atendidas','Abandonadas','Otros'].map((label,i)=>({label,data:ser.map(s=>s[1].length?s[1].filter(statusFns[i]).length/s[1].length*100:0),backgroundColor:i===2?'#aab7c8':colors[i===0?0:2]})),{scales:{x:{stacked:true,grid:{display:false},ticks:{autoSkip:state.grain!=='month',maxTicksLimit:6,maxRotation:0,font:{size:12}}},y:{stacked:true,beginAtZero:true,max:100,ticks:{callback:v=>v+'%'},grid:{color:'#edf1f5'}}},plugins:{tooltip:{...{backgroundColor:'#122238',padding:12},callbacks:{label:ctx=>`${ctx.dataset.label}: ${ctx.parsed.y.toFixed(1)}% · ${fmt(ser[ctx.dataIndex][1].filter(statusFns[ctx.datasetIndex]).length)} llamadas`}}}},i=>trendCross(ser,i));
 heat(data);
 const cl=comp.currRows.length,pl=comp.prevRows.length;chart('callCompare','bar',['Atendidas','Abandonadas'],[{label:'Semana actual',data:[comp.curr.answered,comp.curr.abandoned],backgroundColor:colors[0]},{label:'Semana anterior',data:[comp.prev.answered,comp.prev.abandoned],backgroundColor:'#b0c6e6'}]);
 $('box-callCompare').parentElement.querySelector('.panel-head p').textContent=`${dt(comp.from)} vs. ${dt(comp.previous)} · ${comp.days} día(s)`;
 $('box-callCompare').insertAdjacentHTML('afterend',`<div class="panel-foot">${fmt(cl)} vs. ${fmt(pl)} llamadas. ${pl?`Variación: ${((cl-pl)/pl*100).toFixed(1)}%.`:'Sin base para variación porcentual.'} Referencia: fecha Hasta; mismos filtros de dimensión.</div>`);
 renderMonthlyCalls(data);
 renderHourlyCalls(data);
}
function monthlyPanel(){return '<article class="panel wide monthly-panel" aria-labelledby="monthlyTitle"><div class="panel-head"><div><h2 id="monthlyTitle">Resumen mensual de llamadas</h2><p>Recibidas, atendidas y abandonadas · servicio 08:00–23:00</p></div></div><div class="table-wrap monthly-wrap"><table id="monthlyCallsTable"><caption class="sr-only">Llamadas por mes; los porcentajes se calculan sobre las recibidas de cada mes.</caption></table></div><div class="panel-foot">% atención = atendidas / recibidas · % abandono = abandonadas / recibidas. Selecciona un mes para filtrar.</div></article>';}
function renderMonthlyCalls(data){const f=getFilters(),groups=C.monthlyCalls(data,f.from,f.to),total=C.metrics(data,'calls');const headers=['Mes','Recibidas','Atendidas','% atención','Abandonadas','% abandono'];const cells=g=>`<td class="numeric">${fmt(g.total)}</td><td class="numeric">${fmt(g.answered)}</td><td class="numeric rate attention">${pct(g.attention)}</td><td class="numeric">${fmt(g.abandoned)}</td><td class="numeric rate abandon">${pct(g.total?g.abandoned/g.total:null)}</td>`;$('monthlyCallsTable').innerHTML='<caption class="sr-only">Llamadas por mes; los porcentajes se calculan sobre las recibidas de cada mes.</caption><thead><tr>'+headers.map(h=>`<th scope="col">${h}</th>`).join('')+'</tr></thead><tbody>'+groups.map(g=>`<tr data-month="${g.month}"><th scope="row"><button class="month-link" data-month="${g.month}" aria-label="Filtrar ${monthLabel(g.month)} ${g.month.slice(0,4)}">${monthLabel(g.month)}</button></th>${cells(g)}</tr>`).join('')+(!groups.length?'<tr><td colspan="6">No hay llamadas con estos filtros.</td></tr>':'')+'</tbody><tfoot><tr><th scope="row">Total</th>'+cells(total)+'</tr></tfoot>';$('monthlyCallsTable').querySelectorAll('button[data-month]').forEach(b=>b.onclick=()=>selectMonth(b.dataset.month));}
function hourlyPanel(){return '<article class="panel wide monthly-panel hourly-panel" aria-labelledby="hourlyTitle"><div class="panel-head"><div><h2 id="hourlyTitle">Resumen de llamadas por hora</h2><p>Franjas de una hora · según los filtros actuales</p></div></div><div class="table-wrap monthly-wrap hourly-wrap"><table id="hourlyCallsTable"></table></div><div class="panel-foot">Desde las 08:00 hasta las 23:00. Selecciona una franja para filtrar. Incluye horas estimadas de abandonos.</div></article>';}
function renderHourlyCalls(data){const groups=C.hourlyCalls(data),total=C.metrics(data,'calls');const cells=g=>`<td class="numeric">${fmt(g.total)}</td><td class="numeric">${fmt(g.answered)}</td><td class="numeric">${fmt(g.abandoned)}</td>`;const label=h=>`${String(h).padStart(2,'0')}:00–${String(h+1).padStart(2,'0')}:00`;$('hourlyCallsTable').innerHTML='<caption class="sr-only">Llamadas recibidas, atendidas y abandonadas por franja de una hora, de 08:00 a 23:00, según los filtros actuales.</caption><thead><tr><th scope="col">Franja horaria</th><th scope="col">Recibidas</th><th scope="col">Atendidas</th><th scope="col">Abandonadas</th></tr></thead><tbody>'+groups.map(g=>`<tr data-hour="${g.hour}"><th scope="row"><button class="month-link" data-hour="${g.hour}" aria-label="Filtrar llamadas de ${label(g.hour)}">${label(g.hour)}</button></th>${cells(g)}</tr>`).join('')+'</tbody><tfoot><tr><th scope="row">Total</th>'+cells(total)+'</tr></tfoot>';if(!data.length)$('hourlyCallsTable').insertAdjacentHTML('beforebegin','<p class="hourly-empty" role="status">No hay llamadas con estos filtros.</p>');$('hourlyCallsTable').querySelectorAll('button[data-hour]').forEach(b=>b.onclick=()=>cross('hour',+b.dataset.hour));}
function heat(data){
 const hours=Array.from({length:15},(_,i)=>i+8);const cells=Array.from({length:7},()=>Array.from({length:15},()=>({total:0,answered:0,abandoned:0})));data.forEach(r=>{const d=new Date(r.t),c=cells[(d.getUTCDay()+6)%7][d.getUTCHours()-8];c.total++;c.answered+=r.answered;c.abandoned+=r.abandoned;});const max=Math.max(1,...cells.flat().map(c=>c.total));
 $('box-callHeat').style.height='auto';$('box-callHeat').innerHTML=`<div class="heat-scroll"><div class="heatmap"><span></span>${hours.map(h=>`<span class="hour">${h}:00</span>`).join('')}${cells.map((day,w)=>`<span class="weekday">${['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'][w]}</span>`+day.map((c,i)=>`<button data-weekday="${w}" data-hour="${hours[i]}" aria-label="${['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'][w]} ${hours[i]}:00–${hours[i]+1}:00: ${c.total} llamadas, ${c.answered} atendidas, ${c.abandoned} abandonadas" style="background:${c.total?`rgba(8,127,140,${.15+.85*c.total/max})`:state.theme==='dark'?'#24384f':'#f0f4f8'}"></button>`).join('')).join('')}</div></div><div class="heat-legend">Menor${[0,.25,.5,.75,1].map(n=>`<i style="background:rgba(8,127,140,${.15+.85*n})"></i>`).join('')}Mayor · ${max}</div>`;
 $('box-callHeat').querySelectorAll('button').forEach(b=>{b.onclick=()=>{state.cross={...state.cross,weekday:+b.dataset.weekday,hour:+b.dataset.hour};render();};const show=e=>{const c=cells[+b.dataset.weekday][+b.dataset.hour-8];$('chartTooltip').hidden=false;$('chartTooltip').textContent=`${b.getAttribute('aria-label')}`;const rect=b.getBoundingClientRect();$('chartTooltip').style.left=Math.min(e.clientX||rect.left,window.innerWidth-300)+'px';$('chartTooltip').style.top=Math.max(5,(e.clientY||rect.top)-65)+'px';};b.onmouseenter=show;b.onfocus=show;b.onmouseleave=b.onblur=()=>{$('chartTooltip').hidden=true;};});
}
function renderSales(data,m,ser,comp){
 const leader=C.rankExecutives(data,'transactions')[0];
 $('kpis').innerHTML=card('Ventas totales',cash(m.total),`${fmt(data.length-m.invalidMoney)} registros con monto válido · MXN`,'$')+card('Ticket promedio',cash(m.average),`${fmt(m.validTransactions)} transacciones con monto válido`,'◫')+card('Transacciones',fmt(m.transactions),`Órdenes únicas por fecha y sucursal`,'≡')+card('Líder en número de ventas',leader?esc(leader.name):'—',leader?`${fmt(leader.transactions)} ventas · ${cash(leader.total)}`:'Sin ejecutivos con ventas en el período','★','kpi-leader');
 const top=C.group(data,'region').sort((a,b)=>C.metrics(b[1],'sales').total-C.metrics(a[1],'sales').total)[0];
 $('insights').innerHTML=`<span class="insight-label">LECTURA DEL PERÍODO</span><span>${data.length?`<b>${esc(top?.[0]||'Sin dato')}</b> aporta ${m.total>0?pct(C.metrics(top[1],'sales').total/m.total):'—'} de las ventas. ${state.salesGoal>0?`Cumplimiento de meta del período: <b>${pct(m.total/state.salesGoal)}</b>.`:'Define la meta del período en “Criterios y calidad” para medir cumplimiento.'} ${m.invalidMoney?`${fmt(m.invalidMoney)} registros sin monto válido.`:''}`:'No hay ventas para la selección.'}</span>`;
 $('charts').innerHTML=panel('saleTrend','Evolución de ventas','Venta registrada y tendencia lineal · MXN','Selecciona un punto de venta real para filtrar el período.','wide',state.grain==='week'?'SEMANAL':state.grain==='month'?'MENSUAL':'DIARIO')+panel('saleShare','Ventas por ejecutivo','Top 7 por monto · barras agrupadas por servicio','Excluye SUCURSAL. Selecciona una barra para filtrar.','wide')+panel('saleProducts','Servicios más vendidos','Transacciones por servicio disponible','Se usa SERVICIO; el archivo no incluye productos individuales.')+panel('saleGoal','Cumplimiento de meta','Venta real frente a meta del período','Configura la meta en “Criterios y calidad”.')+panel('saleTicket','Ticket por servicio','Venta / transacciones con monto válido','Las filas sin monto no entran al promedio.')+panel('saleRegion','Ventas por estado / región','Top 10 · MXN','Selecciona una barra para filtrar.','wide')+panel('saleBranches','Ventas por sucursal','Top 10 · MXN','Selecciona una barra para filtrar sucursal.','wide');
 const amounts=ser.map(s=>C.metrics(s[1],'sales').total),trend=C.linearTrend(amounts);const monthLabels=ser.map(s=>{if(state.grain!=='month')return state.grain==='week'?periodLabel(s[0]):dt(s[0]);return monthLabel(s[0]);});
 chart('saleTrend','line',monthLabels,[{label:'Ventas (MXN)',data:amounts,borderColor:colors[0],backgroundColor:'#087f8c12',borderWidth:2,fill:true,tension:.25,pointRadius:2,pointHitRadius:10},{label:'Tendencia lineal',data:trend,borderColor:colors[1],backgroundColor:'transparent',borderWidth:2,borderDash:[6,4],fill:false,tension:0,pointRadius:0,pointHitRadius:0}],{moneyScale:true,scales:{x:{grid:{display:false},border:{display:false},ticks:{autoSkip:state.grain!=='month',maxRotation:0,font:{size:12}}}},plugins:{tooltip:{backgroundColor:'#122238',padding:12,callbacks:{title:ctx=>ctx.length?(state.grain==='month'?new Date(C.date(ser[ctx[0].dataIndex][0]+'-01')).toLocaleDateString('es-MX',{month:'long',year:'numeric',timeZone:'UTC'}):dt(ser[ctx[0].dataIndex][0])):'',label:ctx=>`${ctx.dataset.label}: ${preciseMoney.format(ctx.parsed.y)}`}}}},(i,d)=>{if(d===0)trendCross(ser,i);});
 const ranked=C.rankExecutives(data).slice(0,7),executiveServices=[...new Set(data.map(r=>r.service))].sort((a,b)=>a.localeCompare(b));chart('saleShare','bar',ranked.map(r=>r.name),executiveServices.map((service,i)=>({label:service,data:ranked.map(r=>C.metrics(r.records.filter(x=>x.service===service),'sales').total),backgroundColor:colors[i],grouped:true})),{indexAxis:'y',moneyScale:true,scales:{x:{beginAtZero:true,stacked:false,grid:{color:'#edf1f5'}},y:{stacked:false,grid:{display:false},ticks:{font:{size:12}}}}},i=>cross('agent',ranked[i].name));

 bar('saleProducts',C.group(data,'service'),r=>C.metrics(r,'sales').transactions,'Transacciones','segment');
 gauge('saleGoal',state.salesGoal>0?m.total/state.salesGoal:null,'Cumplimiento de venta',state.salesGoal>0?`${cash(m.total)} de ${cash(state.salesGoal)} · período filtrado`:'Define una meta de venta en “Criterios y calidad”.');
 const services=C.group(data,'service');chart('saleTicket','bar',services.map(g=>g[0]),[{label:'Ticket promedio',data:services.map(g=>C.metrics(g[1],'sales').average),backgroundColor:colors}],{moneyScale:true},i=>cross('segment',services[i][0]));
 bar('saleRegion',C.group(data,'region'),r=>C.metrics(r,'sales').total,'Ventas','region',true);bar('saleBranches',C.group(data,'branch'),r=>C.metrics(r,'sales').total,'Ventas','branch',true);
}
function renderTable(data){const sales=state.type==='sales',sorted=[...data].sort((a,b)=>b.t-a.t||b.id-a.id).slice(0,100);$('tableCaption').textContent=sales?'Registros fuente; una orden puede tener varias filas.':'Sin números de teléfono · hora estimada marcada con *.';const headers=sales?['Fecha','Ejecutivo','Estado','Sucursal','Orden / ticket','Servicio','Venta MXN']:['Fecha / hora','Agente','Cola','Estado','Espera','Atención'];$('detailTable').innerHTML='<thead><tr>'+headers.map(h=>`<th scope="col">${h}</th>`).join('')+'</tr></thead><tbody>'+sorted.map(r=>'<tr>'+(sales?[r.date,r.agent,r.region,r.branch,r.ticket,r.service,r.amount===null?'Monto no válido':preciseMoney.format(r.amount)]:[`${r.date} ${new Date(r.t).toISOString().slice(11,19)}${r.estimated?' *':''}`,r.agent,r.region,r.status,time(r.wait),time(r.talk)]).map((v,i)=>`<td ${sales&&i===6?'class="money"':''}>${!sales&&i===3?`<span class="status ${r.abandoned?'red':''}">${esc(v)}</span>`:esc(v)}</td>`).join('')+'</tr>').join('')+(!sorted.length?`<tr><td colspan="${headers.length}">No hay registros con estos filtros.</td></tr>`:'')+'</tbody>';}
function quality(){let html='';for(const t of ['calls','sales']){const {q,data,name}=state.datasets[t];html+=`<section class="quality-source"><h3>${t==='calls'?'Llamadas FLP':'Ventas'} · ${esc(name)}</h3><div class="quality-stats"><span><b>${fmt(q.raw)}</b>filas originales</span><span><b>${fmt(data.length)}</b>registros incluidos</span><span><b>${fmt(q.duplicates)}</b>duplicados exactos ${state.dedup?'excluidos':'incluidos'}</span></div><p>Fechas inválidas excluidas: ${fmt(q.invalidDate)}.</p>`;if(t==='calls')html+=`<p>Fuera de servicio (excluidas de gráficos y KPIs): ${fmt(data.filter(r=>!C.inService(r)).length)}. Ventana 08:00–23:00.</p><p>Horas estimadas (fin − espera): ${fmt(q.estimated)}. Uso de hora fin sin espera: ${fmt(q.endFallback)}. Esperas ausentes: ${fmt(q.missingWait)}. Duraciones ausentes en atendidas: ${fmt(q.missingTalk)}. Estados sin clasificar: ${fmt(q.unknownStatus)}. FCR válido: ${fmt(q.fcrValid)} atendidas.</p>`;else html+=`<p>Montos excluidos: ${fmt(q.invalidMoney)}. Montos negativos: ${fmt(q.negativeMoney)}. Registros sin ticket utilizable: ${fmt(q.missingTicket)}. Registros con denominadores de conversión: ${fmt(q.conversionValid)}.</p>`;if(q.issues.length)html+=`<p>${q.issues.slice(0,8).map(esc).join('<br>')}${q.issues.length>8?'<br>… Verifica las filas indicadas en tu archivo.':''}</p>`;html+='</section>';}$('qualityReport').innerHTML=html;}
function reset(){const b=bounds();state.f={from:b.min,to:b.max,month:'',agent:'',region:'',segment:'',type:state.type};state.dimensions={calls:{agent:'',region:'',segment:''},sales:{agent:'',region:'',segment:''}};state.cross={};setupFilters();render();}
function csvExport(){const data=rows(),sales=state.type==='sales',header=sales?['Fecha','Ejecutivo','Estado','Sucursal','Orden / ticket','Servicio','TOTAL MXN']:['Fecha/hora','Agente','Cola','Estado','Tiempo Espera (s)','Duración (s)','Hora estimada'];const vals=data.map(r=>sales?[r.date,r.agent,r.region,r.branch,r.ticket,r.service,r.amount]:[new Date(r.t).toISOString().replace('T',' ').slice(0,19),r.agent,r.region,r.status,r.wait,r.talk,r.estimated?'Sí':'No']);const cell=v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const csv='\ufeff'+[header,...vals].map(r=>r.map(cell).join(',')).join('\r\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=`FLP-${state.type}-${state.f.from}-${state.f.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function settings(){const s=+$('slaSeconds').value,g=+$('slaGoal').value,v=$('salesGoal').value.trim();if(!Number.isFinite(s)||s<1||s>3600||!Number.isFinite(g)||g<1||g>100){message('Usa un umbral SLA entre 1 y 3,600 segundos y un objetivo entre 1 y 100%.',true);return;}if(v&&(!Number.isFinite(+v)||+v<0)){message('La meta de venta debe ser un monto positivo.',true);return;}state.sla=s;state.slaGoal=g;state.salesGoal=v?+v:0;state.dedup=$('dedup').checked;rebuild();render();}
function repositoryControls(disabled){document.querySelectorAll('.summary-toolbar input,.summary-toolbar select,.summary-toolbar button,[role="tab"],#exportButton,#methodButton').forEach(el=>el.disabled=disabled);}
function parseRepositoryWorkbook(bytes,type,config){
 const book=XLSX.read(bytes,{type:'array',raw:true,cellDates:false,codepage:65001});
 if(!book.SheetNames.length)throw Error('El archivo no contiene hojas.');
 const names=config.sheet?[config.sheet]:book.SheetNames;let best=null;
 for(const name of names){if(!book.Sheets[name])throw Error(`No existe la hoja ${name}.`);const matrix=XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,raw:true,defval:null,blankrows:false});matrix.slice(0,20).forEach((row,index)=>{const mapping=C.guess(row,type),score=Object.values(mapping).filter(v=>v>=0).length;const required=type==='sales'?mapping.date>=0&&mapping.amount>=0:mapping.status>=0&&(mapping.start>=0||mapping.end>=0);if(required&&(!best||score>best.score))best={matrix,index,mapping,score,name};});}
 if(!best)throw Error(type==='sales'?'Faltan las columnas FECHA y TOTAL.':'Faltan Estado y Hora Inicio o Hora Fin.');
 const source={headers:best.matrix[best.index].map((h,i)=>C.clean(h)||`Columna ${i+1}`),rows:best.matrix.slice(best.index+1),name:config.path.split('/').pop(),sheet:best.name,mapping:best.mapping,date1904:!!book.Workbook?.WBProps?.date1904};
 if(!source.rows.length)throw Error('La hoja no tiene registros.');if(source.rows.length>100000)throw Error('La hoja excede 100,000 filas.');
 const parsed=C.normalize(source,type,state.dedup);if(!parsed.data.length)throw Error('No hay registros con fechas válidas.');if(type==='sales'&&parsed.q.invalidMoney===parsed.data.length)throw Error('No hay importes válidos en TOTAL.');return {source,parsed};
}
async function fetchRepositoryFile(type,stamp){
 const config=window.FLP_FILES?.[type];if(!config?.path||typeof config.path!=='string')throw Error(`Configura la ruta de ${type==='calls'?'llamadas':'ventas'} en config.js.`);
 const url=new URL(config.path,document.baseURI);if(!/\.(xlsx|csv)$/i.test(url.pathname))throw Error('La ruta debe terminar en .xlsx o .csv.');url.searchParams.set('_corte',stamp);
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);
 try{const response=await fetch(url.href,{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error(`HTTP ${response.status}. Revisa que el archivo esté publicado en la carpeta datos.`);if((response.headers.get('content-type')||'').includes('text/html'))throw Error('La ruta devolvió una página HTML en vez de un Excel o CSV.');const bytes=await response.arrayBuffer();if(!bytes.byteLength)throw Error('El archivo está vacío.');if(bytes.byteLength>20*1024*1024)throw Error('El archivo excede 20 MB.');return parseRepositoryWorkbook(bytes,type,config);}
 catch(e){throw Error(`${config.path}: ${e.name==='AbortError'?'La consulta superó 30 segundos.':e.message}`);}finally{clearTimeout(timeout);}
}
async function reloadRepository(){
 if(state.remote.loading)return false;state.remote.loading=true;state.remote.error='';const first=!state.remote.loadedAt,button=$('uploadButton');button.disabled=true;button.textContent='Consultando…';$('remoteStatus').textContent='Consultando archivos…';$('dashboard').setAttribute('aria-busy','true');if(first){$('dashboard').hidden=true;repositoryControls(true);}message('Consultando los archivos del repositorio…');
 try{if(location.protocol==='file:')throw Error('Abre el dashboard desde GitHub Pages o un servidor local; la lectura automática no funciona al abrir index.html con doble clic.');if(!window.XLSX)throw Error('No se pudo cargar el lector de Excel.');const previous=bounds(),fullRange=!state.f.month&&state.f.from===previous.min&&state.f.to===previous.max;const stamp=String(Date.now()),result=await Promise.all(['calls','sales'].map(t=>fetchRepositoryFile(t,stamp)));const next=Object.fromEntries(result.map((r,i)=>[['calls','sales'][i],r]));
 // Both workbooks are validated before either dataset replaces the current cut.
 state.raw={calls:next.calls.source,sales:next.sales.source};state.datasets={calls:next.calls.parsed,sales:next.sales.parsed};state.remote.loadedAt=new Date().toISOString();state.remote.error='';if(first)reset();else{if(fullRange){const nextBounds=bounds();state.f.from=nextBounds.min;state.f.to=nextBounds.max;}for(const t of ['calls','sales']){const data=state.datasets[t].data;for(const field of ['agent','region','segment']){const key=field==='segment'?(t==='calls'?'status':'service'):field;if(state.dimensions[t][field]&&!data.some(r=>C.norm(r[key])===C.norm(state.dimensions[t][field])))state.dimensions[t][field]='';if(t===state.type&&state.f[field]&&!data.some(r=>C.norm(r[key])===C.norm(state.f[field])))state.f[field]='';}}setupFilters();render();}repositoryControls(false);$('dashboard').hidden=false;const checked=new Date(state.remote.loadedAt).toLocaleString('es-MX');$('remoteStatus').textContent=`Última lectura: ${checked}`;$('remoteStatus').title='Hora de consulta de archivos, no fecha de modificación de los Excel.';message(`Datos consultados: ${fmt(state.datasets.calls.data.length)} registros de llamadas y ${fmt(state.datasets.sales.data.length)} registros de ventas.`,false);return true;
 }catch(e){state.remote.error=`No se pudieron actualizar los datos. ${e.message}${first?' Corrige los archivos y pulsa Actualizar datos.':' Se conserva el último corte válido de esta sesión.'}`;message(state.remote.error,true);$('remoteStatus').textContent=first?'Sin datos cargados':`Error de actualización · última lectura válida: ${new Date(state.remote.loadedAt).toLocaleString('es-MX')}`;return false;
 }finally{state.remote.loading=false;button.disabled=false;button.innerHTML='<span aria-hidden="true">↻</span> Actualizar datos';$('dashboard').setAttribute('aria-busy','false');}
}
function registerTools(){if(!document.modelContext?.registerTool)return;const lifetime=new AbortController();const tools=[{name:'leer_resumen_flp',title:'Leer resumen FLP',description:'Lee los indicadores del área y los filtros actuales.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({area:state.type,filters:getFilters(),metrics:C.metrics(rows(),state.type,state.sla)})},{name:'configurar_filtros_flp',title:'Configurar filtros FLP',description:'Cambia el área o los filtros visibles; no modifica los archivos.',inputSchema:{type:'object',properties:{area:{type:'string',enum:['calls','sales']},desde:{type:'string'},hasta:{type:'string'},agente:{type:'string'},region:{type:'string'},segmento:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object')throw Error('Entrada inválida');const allowed=['area','desde','hasta','agente','region','segmento'];if(Object.keys(input).some(k=>!allowed.includes(k)))throw Error('Campo no válido');if(input.area&&!['calls','sales'].includes(input.area))throw Error('Área inválida');for(const k of ['desde','hasta'])if(input[k]!==undefined&&(!/^\d{4}-\d{2}-\d{2}$/.test(input[k])||C.date(input[k])===null))throw Error('Fecha inválida');const from=input.desde??state.f.from,to=input.hasta??state.f.to;if(from>to)throw Error('Rango inválido');const type=input.area??state.type,d=state.datasets[type].data;for(const [k,field]of [['agente','agent'],['region','region'],['segmento',type==='calls'?'status':'service']]){if(input[k]!==undefined&&typeof input[k]!=='string')throw Error('Filtro inválido');if(input[k]&& !d.some(r=>r[field]===input[k]))throw Error('Filtro desconocido');}if(type!==state.type)setTab(type);state.f={...state.f,month:'',from,to,...(input.agente!==undefined?{agent:input.agente}:{}),...(input.region!==undefined?{region:input.region}:{}),...(input.segmento!==undefined?{segment:input.segmento}:{})};state.cross={};setupFilters();render();return {area:state.type,filters:getFilters(),records:rows().length};}}];tools.forEach(tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch(_){}});window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});}
function init(){rebuild();const b=bounds();state.f.from=b.min;state.f.to=b.max;if(window.Chart){Chart.defaults.font.family='Inter, Arial, sans-serif';Chart.defaults.color='#63738a';}setupFilters();render();$('tabCalls').onclick=()=>setTab('calls');$('tabSales').onclick=()=>setTab('sales');for(const id of ['fromDate','toDate','agentFilter','segmentFilter'])$(id).onchange=()=>{const field={fromDate:'from',toDate:'to',agentFilter:'agent',segmentFilter:'segment'}[id];state.f[field]=$(id).value;if((field==='from'||field==='to')&&!state.f[field]){const b=bounds();state.f[field]=field==='from'?b.min:b.max;$(id).value=state.f[field];}if(field==='from'||field==='to'){state.f.month='';setupFilters();}state.cross={};render();};$('monthFilter').onchange=()=>selectMonth($('monthFilter').value);$('themeToggle').onclick=()=>applyTheme(state.theme==='dark'?'light':'dark');$('grain').onchange=()=>{state.grain=$('grain').value;state.grains[state.type]=state.grain;render();};$('resetButton').onclick=reset;$('exportButton').onclick=csvExport;$('uploadButton').onclick=()=>reloadRepository();$('methodButton').onclick=()=>{$('methodDialog').showModal();quality();};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());['slaSeconds','slaGoal','salesGoal','dedup'].forEach(id=>$(id).onchange=settings);document.querySelectorAll('[role="tab"]').forEach(t=>t.onkeydown=e=>{if(['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();setTab(state.type==='calls'?'sales':'calls');$(state.type==='calls'?'tabCalls':'tabSales').focus();}});let savedTheme='light';try{savedTheme=localStorage.getItem('flp-theme')||'light';}catch(_){}applyTheme(['light','dark'].includes(savedTheme)?savedTheme:'light',false);registerTools();window.FLPDashboard={state,setTab,cross,render,rows,reset,selectMonth,applyTheme,reloadRepository};window.FLPDashboard.ready=reloadRepository();}
init();
})();
